### PR TITLE
add hpe ilo 4 custom_scripts

### PR DESCRIPTION
**Pull request by lazharh**

### CODE REVIEW

**Comment by mvazquezc** [comment]
lgtm

**Comment by dtantsur** [comment]
Does it needs to be so specific? I mean, will it not work for other iLO4 models?

**Comment by lazharh** [comment]
I hope so, I did not try it on every hpe model

**Comment by dtantsur** [comment]
Could you maybe remove the model name to avoid confusion?

**Comment by lazharh** [comment]
updated folder name

**Pull request merged**
